trixtateam/trixta-js

package.json
src/React/reducers/__mocks__/trixtaState.js
src/React/reducers/tests/reducers.test.js
src/React/reducers/trixtaReducer.js
src/React/sagas/setupTrixtaSaga.js
src/React/selectors/tests/selectors.test.js
src/React/selectors/trixtaActions.js
src/React/selectors/trixtaReactions.js

fix: check for agent details role before authorization

fix: joinTrixtaRole even if no response

---

package.json
src/React/reducers/__tests__/reducers.test.js
src/React/reduxActions/common.ts
src/React/reduxActions/internal/index.ts
src/React/reduxActions/trixtaActions.ts
src/React/reduxActions/trixtaReactions.ts
src/React/sagas/respondToTrixtaReactionEffectSaga.ts
src/React/sagas/setupTrixtaSaga.ts
src/React/types.ts
src/React/types/actions/index.ts
src/React/types/reactions/index.ts

feat: fork updating actions and reactions on a role

---

package.json
src/React/constants/index.ts
src/React/reducers/__tests__/reducers.test.js
src/React/reducers/trixtaReducer.ts
src/React/reduxActions/internal/index.ts
src/React/reduxActions/tests/actions.test.js
src/React/sagas/setupTrixtaSaga.ts
src/React/types/common/index.ts
src/React/types/reactions/index.ts
yarn.lock

feat: use separated additionalData from phoenix response

---

package.json
src/React/global.d.ts
src/React/hooks/index.ts
src/React/hooks/use-trixta-action-reaction/use-trixta-action-reaction.ts
src/React/hooks/use-trixta-action/use-trixta-action.ts
src/React/hooks/use-trixta-reaction/use-trixta-reaction.ts
yarn.lock

fix: check trixta action parameters for changes on autosubmit

---

package.json
src/React/hooks/use-trixta-action-reaction/index.test.tsx
src/React/hooks/use-trixta-action-reaction/use-trixta-action-reaction.ts
src/React/hooks/use-trixta-action/types.ts
src/React/hooks/use-trixta-action/use-trixta-action.ts
src/React/hooks/use-trixta-reaction/index.test.tsx
src/React/hooks/use-trixta-reaction/use-trixta-reaction.ts
src/React/selectors/tests/actions/selectors.test.js
src/React/selectors/tests/reactions/selectors.test.js
src/React/selectors/trixtaActions.ts
src/React/selectors/trixtaReactions.ts

feat: include loading state for reaction and action hooks

---

docs/react/trixta/sagas.md
package.json
src/React/components/actions/TrixtaActionComponent/TrixtaActionComponent.tsx
src/React/components/reactions/RespondToReactionComponent/RespondToReactionComponent.tsx
src/React/components/reactions/TrixtaReactionInstanceComponent/TrixtaReactionInstanceComponent.tsx
src/React/hooks/use-respond-to-reaction-effect/index.test.tsx
src/React/hooks/use-respond-to-reaction-effect/use-respond-to-reaction-effect.ts
src/React/hooks/use-trixta-action/index.test.tsx
src/React/hooks/use-trixta-reaction/index.test.tsx
src/React/reducers/__tests__/reducers.test.ts
src/React/reducers/trixtaReducer.ts
src/React/reduxActions/common.ts
src/React/reduxActions/internal/index.ts
src/React/reduxActions/tests/actions.test.ts
src/React/reduxActions/trixtaActions.ts
src/React/reduxActions/trixtaReactions.ts
src/React/reduxActions/types/common.ts
src/React/reduxActions/types/trixtaActions.ts
src/React/reduxActions/types/trixtaReactions.ts
src/React/sagas/respondToTrixtaReactionEffectSaga.ts
src/React/sagas/setupTrixtaSaga.ts
src/React/types/common/index.ts
src/React/types/reactions/index.ts

feat: action data renamed to payload

---

.github/workflows/ci.yml
.github/workflows/semantic-release.yml
package.json
release.config.js

chore(release): test CI

---

src/React/hooks/use-trixta-action/index.test.tsx
src/React/hooks/use-trixta-action/use-trixta-action.ts
src/React/hooks/use-trixta-reaction/index.test.tsx
src/React/hooks/use-trixta-reaction/use-trixta-reaction.ts
src/React/selectors/tests/actions/selectors.test.js
src/React/selectors/tests/reactions/selectors.test.js
src/React/selectors/trixtaActions.ts
src/React/selectors/trixtaReactions.ts

fix: loadingStatusRef for hooks

---

.github/workflows/publish-release.yml
.github/workflows/semantic-release.yml
.storybook/preview.js
src/React/reducers/trixtaReducer.ts
src/React/reduxActions/stories/common/removeTrixtaRole/removeTrixtaRole.stories.mdx
src/React/reduxActions/stories/common/signoutTrixta/signoutTrixta.stories.mdx
src/React/reduxActions/stories/common/updateTrixtaRole/updateTrixtaRole.stories.mdx
src/React/reduxActions/stories/common/updateTrixtaRoles/updateTrixtaRoles.stories.mdx
src/React/selectors/common.ts
src/stories/Introduction.stories.mdx
src/stories/reduxStore/Actions.stories.mdx
src/stories/reduxStore/Preview.stories.mdx
src/stories/reduxStore/Reactions.stories.mdx
src/stories/utils/JsonViewer.tsx
src/stories/utils/TrixtaReduxPreview.tsx

feat: document redux store

---

.github/workflows/semantic-release.yml
src/React/components/actions/TrixtaActionComponent/TrixtaActionComponent.tsx
src/React/components/actions/TrixtaActionComponent/types.ts
src/React/components/reactions/TrixtaReactionComponent/types.ts
src/React/components/reactions/TrixtaReactionInstanceComponent/TrixtaReactionInstanceComponent.tsx
src/React/components/reactions/TrixtaReactionInstanceComponent/types.ts
src/React/hooks/use-trixta-action/index.test.tsx
src/React/hooks/use-trixta-action/use-trixta-action.ts
src/React/hooks/use-trixta-reaction/index.test.tsx
src/React/hooks/use-trixta-reaction/use-trixta-reaction.ts
src/React/reducers/__tests__/reducers.test.ts
src/React/reducers/trixtaReducer.ts
src/React/reduxActions/internal/actions/types.ts
src/React/reduxActions/internal/reactions/types.ts
src/React/reduxActions/types/trixtaActions.ts
src/React/reduxActions/types/trixtaReactions.ts
src/React/sagas/setupTrixtaSaga.ts
src/React/types/actions/index.ts
src/React/types/common/index.ts
src/React/types/reactions/index.ts

extraData parameter for submitTrixtaActionResponse and submitTrixtaReactionResponse to pass onto response

feat: extraData parameter to pass onto response

---

jest.config.js
src/React/components/reactions/TrixtaReactionComponent/TrixtaReactionComponent.stories.tsx
src/React/components/reactions/TrixtaReactionComponent/TrixtaReactionComponent.tsx
src/React/components/reactions/types.ts
src/React/constants/index.ts
src/React/hooks/use-trixta-action/use-trixta-action.ts
src/React/hooks/use-trixta-reaction/use-trixta-reaction.ts
src/React/reducers/__mocks__/trixtaState.ts
src/React/reducers/__tests__/reducers.test.ts
src/React/reducers/trixtaReducer.ts
src/React/reduxActions/types/trixtaReactions.ts
src/React/sagas/setupTrixtaSaga.ts
src/React/types/common/index.ts
src/React/types/reactions/index.ts
src/utils/trixta.ts

feat: response instances with timeStamp

---

.github/workflows/npm.yml
.github/workflows/semantic-release.yml
src/React/hooks/use-respond-to-reaction-effect/index.test.tsx
src/React/hooks/use-respond-to-reaction-effect/types.ts
src/React/hooks/use-respond-to-reaction-effect/use-respond-to-reaction-effect.ts
src/React/hooks/use-trixta-action/index.test.tsx
src/React/hooks/use-trixta-action/types.ts
src/React/hooks/use-trixta-action/use-trixta-action.ts
src/React/hooks/use-trixta-reaction/types.ts
src/React/hooks/use-trixta-reaction/use-trixta-reaction.ts

feat: callback function for use-respond-to-reaction-effect

---

src/React/components/TrixtaAuthComponent/TrixtaAuth.stories.tsx
src/React/components/TrixtaAuthComponent/TrixtaAuthComponent.tsx
src/React/components/TrixtaAuthComponent/index.ts
src/React/components/TrixtaAuthComponent/types.ts
src/React/components/index.ts
src/React/hooks/use-trixta-action-reaction/use-trixta-action-reaction.ts
src/React/hooks/use-trixta-action/index.test.tsx
src/React/hooks/use-trixta-reaction/use-trixta-reaction.ts

feat: added trixta auth component

---

src/React/constants/index.ts
src/React/hooks/use-trixta-action/index.test.tsx
src/React/hooks/use-trixta-action/use-trixta-action.ts
src/React/reducers/trixtaReducer.ts
src/React/reduxActions/internal/index.ts
src/React/reduxActions/internal/types.ts
src/React/reduxActions/types.ts
src/tests/helpers/index.tsx

- useTrixtaAction hook will resubmit with autoSubmit option should role access change

feat: should role access change, autosubmit for useTrixtaAction will resubmit

---

.storybook/manager.js
package.json

deps: update rsjf

---

src/React/hooks/index.ts
src/React/hooks/types.ts
src/React/hooks/use-trixta-access/docs-generator.tsx
src/React/hooks/use-trixta-access/index.test.tsx
src/React/hooks/use-trixta-access/types.ts
src/React/hooks/use-trixta-access/use-trixta-access.ts
src/React/hooks/use-trixta-access/useTrixtaAccess.stories.tsx

- useTrixtaAccess hook to determine if the user has access to the roles

feat: useTrixtaAccess hook

---

package.json
src/React/__tests__/general.test.ts
src/React/components/TrixtaFormComponent/index.tsx
src/utils/trixta.ts
yarn.lock

- update RSJF optional dependency and make use submitButtonOptions

feat: update RSJF and make use of submitButtonOptions

---

src/React/__tests__/general.test.ts
src/React/components/TrixtaFormComponent/index.tsx
src/React/components/reactions/TrixtaReactionInstanceComponent/TrixtaReactionInstanceComponent.tsx
src/utils/trixta.ts

-RSJF submitButtonOptions can overide trixta action button behaviour

feat: allow no_render option for trixta actions

---

README.md
docs/README.md
src/React/__tests__/general.test.ts
src/React/components/TrixtaFormComponent/index.tsx
src/React/components/actions/TrixtaActionComponent/TrixtaActionComponent.tsx
src/React/components/actions/TrixtaActionComponent/types.ts
src/React/components/reactions/TrixtaReactionComponent/TrixtaReactionComponent.tsx
src/React/components/reactions/TrixtaReactionComponent/types.ts
src/React/components/reactions/TrixtaReactionInstanceComponent/TrixtaReactionInstanceComponent.tsx
src/React/components/reactions/TrixtaReactionInstanceComponent/types.ts
src/React/widgets/TrixtaLoginWidget/types.ts
src/index.ts
src/utils/trixta.ts

- removed loadingText prop and use progressText from Trixta ui:submitButtonOptions

feat: removed loadingText prop and use progressText from Trixta ui:submitButtonOptions

---

src/React/components/TrixtaAuthComponent/TrixtaAuthComponent.tsx
src/React/components/TrixtaAuthComponent/types.ts
src/React/components/TrixtaFormComponent/index.tsx
src/React/components/actions/TrixtaActionComponent/TrixtaActionComponent.tsx
src/React/components/actions/TrixtaActionComponent/types.ts
src/React/components/actions/TrixtaActionResponseComponent/types.ts
src/React/components/reactions/RespondToReactionsComponent/RespondToReactionsComponent.tsx
src/React/components/reactions/TrixtaReactionComponent/types.ts
src/React/components/reactions/TrixtaReactionInstanceComponent/types.ts
src/React/widgets/TrixtaLoginWidget/TrixtaLoginWidget.tsx
src/stories/utils/FormComponent.tsx

fix: children type props

---

src/React/components/actions/TrixtaActionResponseComponent/types.ts

fix: missing type import

---

.github/workflows/npm.yml
.github/workflows/semantic-release.yml
packages/core/release.config.cjs
packages/rjsf/release.config.cjs
yarn.lock

- update ci to use semantic release and publish packages only on success

ci: semantic release and publish

---

packages/core/src/React/hooks/use-respond-to-reaction-effect/use-respond-to-reaction-effect.ts
packages/core/src/React/hooks/use-respond-to-reaction-response/types.ts
packages/core/src/React/hooks/use-respond-to-reaction-response/use-respond-to-reaction-response.ts
packages/core/src/React/hooks/use-trixta-reaction/types.ts
packages/core/src/React/hooks/use-trixta-reaction/use-trixta-reaction.ts
packages/core/src/React/selectors/trixtaReactions.ts
packages/core/src/React/types/actions/index.ts
packages/core/src/React/types/common/index.ts
packages/core/src/React/types/reactions/index.ts

- added type documentation for Action and Reaction

chore: update comments and moved reaction types

---

packages/core/package.json
packages/rjsf/package.json

chore(dump): update the versions to 2.0.0.alpha.1
